### ISSUE TITLE
MAGICEventSource reads Star, SuperStar, or Melibea files?

### ISSUE THREAD

**Issue by YoshikiOhtani** [cta-observatory/ctapipe_io_magic#37]
The current `MAGICEventSource` can only read the calibrated level files and produce the generator, but I see that there are still some descriptions of the data level confirmation of the input data (e.g., `get_run_info_from_name`). I think those lines were written because the `MAGICEventSource` could read the other levels of the MAGIC data in the past, but now it is not the case. So I have a question, is there still a plan for the development to make the `MAGICEventSource` possible to reads the other levels of the data? Or do we fix the ability of the `MAGICEventSource` just to read only the calibrated level data?

If it is the latter case, we can simplify the code and also remove the "mars_datalevels.py" script because it is obvious that the input data is in the calibrated level.

**Comment by jsitarek** [comment]
Hi @YoshikiOhtani 
we can discuss it in the Wednesday meeting. 
In general I think it would be good to recover the support for reading other types of MAGIC data, there are a few reasons for this:
1) reading star files (and maybe also superstar) would simplify the CI tests of the cleaning and parametrization of images
2) while starting from MAGIC calibrated files is a good compromise we can consider starting from star (which should already have all the information needed for the common analysis, while keeping the file sizes and processing time much smaller), or the other way around to reimplement the calibration procedure (hopefully not :-) ) to have everything processed consistently between data and MCs.

**Comment by aleberti** [comment]
Hi,

the MAGICEventSource was not able to read star, superstar and melibea in the past. However my plan was to have such possibility,  for the reasons mentioned by Julian. That's why I introduced already the possibility to check for the data levels. At the moment I know that there is a problem reading in star data related to some trees which are present in calibrated files, but not in star ones, which are used to get the prescaler table. Indeed for me it would be useful to have this working with star because I use it in some scripts of magic-cta-pipe to compare the images. Therefore I will work on this as soon the other two PRs to include the bad pixels are merged.

**Comment by YoshikiOhtani** [comment]
Hi, ok thanks for your comments and clarification, I thought that the module could read the other types of MAGIC data in the past, but probably I remembered wrongly. Then I don't have any objections for this, and I agree that we can discuss which types of data should be read by the module for future convenience. I'm closing this issue (question).
